tokens:
  WETH:
    name: "Wrapped Ether"
    symbol: "WETH"
    decimals: 18
    mintAmount: 1
    stable: false
  USDC:
    name: "USD Coin"
    symbol: "USDC"
    decimals: 6
    mintAmount: 1000
    stable: true
  DAI:
    name: "Dai Stablecoin"
    symbol: "DAI"
    decimals: 18
    mintAmount: 1000
    stable: true
  sUSD:
    name: "Synth sUSD"
    symbol: "sUSD"
    decimals: 18
    mintAmount: 1000
    stable: true
  BUSD:
    name: "Binance USD"
    symbol: "BUSD"
    decimals: 18
    mintAmount: 1000
    stable: true
  GYD:
    name: "Gyroscope Dollar"
    symbol: "GYD"
    decimals: 18
    stable: true

pools:
  usdc_busd:
    name: usdc_busd
    assets:
      - symbol: USDC
        amount: 50000000
        weight: 5
      - symbol: BUSD
        amount: 50000000
        weight: 5
    swap_fee: 1000
  dai_weth:
    name: dai_weth
    assets:
      - symbol: DAI
        amount: 50000000
        weight: 5
      - symbol: WETH
        amount: 50000000
        weight: 5
    swap_fee: 1000
  susd_weth:
    name: susd_weth
    assets:
      - symbol: sUSD
        amount: 50000000
        weight: 5
      - symbol: WETH
        amount: 50000000
        weight: 5
    swap_fee: 1000
  gyd_usdc:
    name: gyd_usdc
    assets:
      - symbol: GYD
        amount: 10000000
        weight: 5
      - symbol: USDC
        amount: 10000000
        weight: 5
    swap_fee: 1000

deployments:
  localhost:
    pools:
      - name: usdc_busd
        weight: 34
      - name: dai_weth
        weight: 33
      - name: susd_weth
        weight: 33
      - name: gyd_usdc
        weight: 0
    tokens:
      - symbol: WETH
      - symbol: USDC
      - symbol: DAI
      - symbol: BUSD
      - symbol: sUSD
    oracles:
      - name: UniswapAnchoredView
        contract: DummyUniswapAnchoredView
        args: []
        ownable: true
      - name: "CompoundPriceWrapper"
        args: ["address:UniswapAnchoredView"]
    tokenOracles:
      WETH: CompoundPriceWrapper
      USDC: CompoundPriceWrapper
      DAI: CompoundPriceWrapper
      sUSD: CompoundPriceWrapper
      BUSD: CompoundPriceWrapper
    memoryParam: "999993123563518195"

  kovan:
    pools:
      - name: usdc_busd
        weight: 34
      - name: dai_weth
        weight: 33
      - name: susd_weth
        weight: 33
      - name: gyd_usdc
        weight: 0
    bfactory: "0x8f7F78080219d4066A8036ccD30D588B416a40DB"
    tokens:
      - symbol: WETH
      - symbol: USDC
      - symbol: DAI
      - symbol: BUSD
      - symbol: sUSD
    oracles:
      - name: UniswapAnchoredView
        contract: DummyUniswapAnchoredView
        args: []
        ownable: true
      - name: "CompoundPriceWrapper"
        args: ["address:UniswapAnchoredView"]
    tokenOracles:
      WETH: CompoundPriceWrapper
      USDC: CompoundPriceWrapper
      DAI: CompoundPriceWrapper
      sUSD: CompoundPriceWrapper
      BUSD: CompoundPriceWrapper
    memoryParam: "999993123563518195"
